default: &default
 adapter: postgresql
 encoding: unicode
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
 <<: *default
 database: oyga_development
 username: hernan
 password: root

test:
 <<: *default
 database: oyga_test
 username: hernan
 password: root

production:
 <<: *default
 url: <%= ENV['DATABASE_URL'] %>
